name: deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Clean npm cache
        run: |
          rm -rf node_modules
          rm -f package-lock.json
      - name: 📥 Install dependencies
        run: npm ci
      - name: Update Rollup
        run: npm install rollup@latest
      - name: 🏗️ Build
        run: npm run build --verbose
      - name: 🚀Deploy to GitHub Pages🚀
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
